#!/bin/bash

main(){
#first pass the real xdg-user-dirs-update command

/usr/bin/xdg-user-dirs-update.real "$@"

sleep 0.5

##populate Desktop Folder if it exist

configfolder="$HOME/.config/MX-Linux"
targetfolder="$(xdg-user-dir DESKTOP)"
xdg_checkfile="xdg_check"
liveapplist="minstall.desktop"

applist="FAQ.desktop \ 
Help.desktop"

#check to see if we need to do anything else

if [ -e "$configfolder/$xdg_checkfile" ]; then
	exit 0
fi

#check for live

if [ -e "/live/linux" ]; then
	#special case, check for Installer.desktop
	if [ ! -e "$HOME/Desktop/Installer.desktop" ]; then 
		copystuff "$liveapplist"
	fi
fi

#copy everything else
copystuff "$applist"

#mark so we don't do it again

if [ ! -d "$configfolder" ]; then
	mkdir -p "configfolder"
fi

touch "$configfolder/$xdg_checkfile"
}

copystuff(){
if [ -d "$targetfolder" ]; then
	for i in $1; do
		if [ ! -e "$targetfolder/$i" ]; then
			if [ -e "/usr/share/applications/$i" ]; then
				cp "/usr/share/applications/$i" "$targetfolder" 
			fi
		fi
	done
fi
}

main
exit 0
