#!/bin/bash

##/local/bin/quick-system-info-mx
##wrapper script for inxi to do quick "inxi -F" and copy report to clipboard
##part of mx-goodies package
## changes to optimze inxi run

#requires xsel package

##locale stuff

TEXTDOMAINDIR=/usr/share/locale/ 
export TEXTDOMAIN="mx-goodies"

#setup

main(){

    #check for existing of inxi

    command -v inxi  >/dev/null || quit_error "$(gettext -d $TEXTDOMAIN  'Required inxi app not found')"

    run_report

    quit

}

run_report(){

	local color="$( ( echo VIRT_TERM_COLOR_SCHEME=2; grep -sh '^VIRT_TERM_COLOR_SCHEME=' /etc/inxi.conf ~/.config/inxi.conf) | sed 's/^VIRT_TERM_COLOR_SCHEME=//' | tail -1)"
    echo
    bash -c "inxi -Fxxxrza -c$color | tee >( ( echo '['code']'; sed -E 's/\x1b\[([0-9]{1,2}(;[0-9]{1,2})?)?m//g'; echo '[/'code']' ) | xsel -ib 2>/dev/null )"
    echo
    echo "$(gettext -d $TEXTDOMAIN  'Report copied to system clipboard')"

}

quit(){
    echo
    read -n 1 -s -r -p "$(gettext -d $TEXTDOMAIN  'Press any key to close') "
    exit 0
}

quit_error(){
    local msg
    msg=$1
    echo "$msg"
    exit 1
}

main "$@"
