#!/bin/bash

#DEBHELPER#

# postrm script for cryptsetup-modified-functions

#set -e

case "$1" in
  purge|remove) dpkg-divert --quiet                                               \
                            --remove                                              \
                            --package mx-goodies               \
                            --rename                                              \
                            --divert /usr/bin/xdg-user-dirs-update.real \
                             /usr/bin/xdg-user-dirs-update
                ;;

             *) :
                ;;
esac 

exit 0
