#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    #add brightness-init script to restore brightness after reboot
    if [ ! -e /etc/init.d/brightness-init ]; then
    cp /usr/share/mx-system/brightness-init /etc/init.d/brightness-init
    update-rc.d brightness-init defaults
    fi
    #add /var/cache/brightness-init to excludes files if they don't exist already
    [ "$(grep -q brightness-settings-cache /usr/local/share/excludes/live-remaster-exclude.list && echo $?)" = "0" ]] || echo "var/cache/brightness-settings-cache/*" >> /usr/local/share/excludes/live-remaster-exclude.list
    [ "$(grep -q brightness-settings-cache /usr/local/share/excludes/mx-snapshot-exclude.list && echo $?)" = "0" ]] || echo '\n'"#added to remove saved brightness values of specific machine"'\n'"var/cache/brightness-settings-cache/*" >> /usr/local/share/excludes/mx-snapshot-exclude.list
fi

#DEBHELPER#
