#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    
    #don't do anything if update-rc.d is not present
    if [ -x /usr/sbin/update-rc.d ]; then
       
		if [ -e /etc/init.d/efimount ]; then
		update-rc.d efimount defaults
		fi
	fi
fi

#DEBHELPER#
