#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    #add brightness-init script to restore brightness after reboot
    if [ ! -e /etc/init.d/brightness-init ]; then
    cp /usr/share/mx-system/brightness-init /etc/init.d/brightness-init
    update-rc.d brightness-init defaults
    fi
fi

#DEBHELPER#
