#!/bin/sh

#DEBHELPER#


#set -e

case "$1" in
  install|upgrade) dpkg-divert --quiet                           \
                               --add                             \
                               --package mx-goodies              \
                               --rename                          \
                               --divert /usr/bin/efibootmgr.real \
                               /usr/bin/efibootmgr
                               ;;
esac 

exit 0
